server:
  port: @server.port@
management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false

spring:
  application:
    name: @project.name@
  output:
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari.maximum-pool-size: 10
    hikari.idle-timeout: 30000
  flyway:
    schemas: wb_dispatch
    url: @db.url@

info:
  version: @project.version@
  stage: dev

kafka:
  bootstrap.servers: "localhost:29092"
  topic:
    webhook:
      forward: webhook-forward
      first.retry: webhook-first-retry
      second.retry: webhook-second-retry
      third.retry: webhook-third-retry
      last.retry: webhook-last-retry
      dead.letter.queue: webhook-dead-letter-queue
  concurrency:
    forward: 1
    first.retry: 1
    second.retry: 1
    third.retry: 1
    last.retry: 1
    dead.letter.queue: 1
  ssl:
    enable: false
    keystore-location: src/main/resources/cert/kenny-k.struzhkin.p12
    keystore-password: kenny
    key-password: kenny
    server-password: kenny12
    server-keystore-location: src/

merchant.timeout: 10

riak:
  address: localhost
  port: 8087
  bucket: webhook

retry:
  first.seconds: 30
  second.seconds: 600
  third.seconds: 1800
  last.seconds: 6400
  dead.time.hours: 24